test:
    image: registry.gitlab.com/craigbarnes/dockerfiles/lua-testing
    script:
        - make check LUA=lua5.4
        - make check LUA=lua5.3
        - make check LUA=lua5.2
        - make check LUA=lua5.2
