LUA ?= lua
CURL ?= curl
CURLFLAGS ?= -sSL
NCURSES_SNAPSHOTS = https://raw.githubusercontent.com/ThomasDickey/ncurses-snapshots
TERMINFO_SRC_ORIG = $(NCURSES_SNAPSHOTS)/master/misc/terminfo.src
OUTPUT_FILENAME = $(addprefix examples/output/, $(addsuffix .txt, $(1)))
RUN_EXAMPLE = $(strip $(LUA) $(filter %.lua, $^) $(EXTRA_ARGS))
PRINT_HEADING = printf 'Output generated by `%s`:\n\n' '$(RUN_EXAMPLE)'
GEN_OUTPUT = ($(PRINT_HEADING) && $(RUN_EXAMPLE))

OUTPUT_BASIC = $(call OUTPUT_FILENAME, \
    backspace-key-sends-bs backspace-key-sends-del backspace-key-values \
    cap-names delete-key-sends-del has-auto-margins has-repeat-char \
    longest-key-sequence longest-sequence longest-term-names )

# Example output files that take extra command-line arguments
OUTPUT_EXTRA = $(call OUTPUT_FILENAME, \
    cap-values-Ms )

examples/output/cap-values-Ms.txt: examples/cap-values.lua
examples/output/cap-values-Ms.txt: EXTRA_ARGS = -v Ms

update: update-terminfo example-outputs
example-outputs: $(OUTPUT_BASIC) $(OUTPUT_EXTRA)

check:
	$(LUA) test/basic.lua
	$(LUA) test/errors.lua

$(OUTPUT_BASIC): examples/output/%.txt: examples/%.lua terminfo.src
	$(GEN_OUTPUT) > $@

$(OUTPUT_EXTRA): examples/output/%.txt: terminfo.src
	$(GEN_OUTPUT) > $@

update-terminfo:
	$(CURL) $(CURLFLAGS) -O '$(TERMINFO_SRC_ORIG)'


.DEFAULT_GOAL = check
.PHONY: update update-terminfo example-outputs check
.DELETE_ON_ERROR:
